// Package provider — data-source implementation for
// `laravelcloud_websocket_app`. Reads an existing environment↔WS-cluster
// binding by ID + hydrates cluster ID, env ID, max connections, app
// key, status, timestamps.
//
// Consumers use this data source when composing Terraform modules that
// need to REFERENCE a WS binding provisioned out-of-band. Read-only —
// no CRUD.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/figentra/terraform-provider-laravel-cloud/internal/api"
)

// WebsocketAppDataSource implements the plugin-framework `DataSource`
// contract.
type WebsocketAppDataSource struct {
	// client is the shared authenticated Cloud API wrapper.
	client *api.Client
}

// WebsocketAppDataSourceModel mirrors the resource-side model. Only `id`
// is Required; every other field is Computed.
type WebsocketAppDataSourceModel struct {
	// ID is the Cloud-assigned WS app binding ULID. REQUIRED input.
	ID types.String `tfsdk:"id"`

	// ClusterID is the parent WebsocketCluster.
	ClusterID types.String `tfsdk:"cluster_id"`

	// EnvironmentID is the Cloud environment the binding attaches to.
	EnvironmentID types.String `tfsdk:"environment_id"`

	// MaxConnections is the per-app concurrent-connection cap. Nullable —
	// null means "inherit the cluster's cap".
	MaxConnections types.Int64 `tfsdk:"max_connections"`

	// AppKey is the WebSocket auth secret Cloud generates at bind time.
	// Sensitive — consumers should read via `sensitive` output.
	AppKey types.String `tfsdk:"app_key"`

	// Status is Cloud's lifecycle state.
	Status types.String `tfsdk:"status"`

	// CreatedAt is the RFC3339 timestamp of binding creation.
	CreatedAt types.String `tfsdk:"created_at"`
}

// NewWebsocketAppDataSource is the factory the provider registers.
func NewWebsocketAppDataSource() datasource.DataSource {
	return &WebsocketAppDataSource{}
}

// Metadata sets the data-source type name.
func (d *WebsocketAppDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_websocket_app"
}

// Schema declares the read-only surface.
func (d *WebsocketAppDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Reads an existing Laravel Cloud environment↔WebSocket-cluster " +
			"binding by ID. Useful when composing modules that reference a WS " +
			"binding provisioned in a separate state OR via the Cloud dashboard.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Cloud-assigned WebSocket app binding ID (ULID).",
				Required:            true,
			},
			"cluster_id": schema.StringAttribute{
				MarkdownDescription: "ID of the parent WebSocket cluster.",
				Computed:            true,
			},
			"environment_id": schema.StringAttribute{
				MarkdownDescription: "ID of the bound environment.",
				Computed:            true,
			},
			"max_connections": schema.Int64Attribute{
				MarkdownDescription: "Per-app concurrent-connection cap. Null means " +
					"inherit the parent cluster's cap.",
				Computed: true,
			},
			"app_key": schema.StringAttribute{
				MarkdownDescription: "WebSocket authentication key generated by Cloud. " +
					"Sensitive.",
				Computed:  true,
				Sensitive: true,
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "Cloud lifecycle status.",
				Computed:            true,
			},
			"created_at": schema.StringAttribute{
				MarkdownDescription: "RFC3339 timestamp of binding creation.",
				Computed:            true,
			},
		},
	}
}

// Configure pulls the shared client from ProviderData.
func (d *WebsocketAppDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*api.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *api.Client, got: %T. Please report this issue.",
				req.ProviderData),
		)
		return
	}

	d.client = client
}

// Read hydrates state from Cloud.
func (d *WebsocketAppDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data WebsocketAppDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Fire the read against Cloud.
	app, err := d.client.GetWebsocketApp(ctx, data.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Failed to read websocket app binding",
			"Cloud API returned an error. Original error: "+err.Error(),
		)
		return
	}

	// Hydrate. cluster_id + environment_id are non-nullable per the API
	// contract; max_connections, app_key, status, created_at may be null.
	data.ClusterID = types.StringValue(app.ClusterID)
	data.EnvironmentID = types.StringValue(app.EnvironmentID)

	if app.MaxConnections != nil {
		data.MaxConnections = types.Int64Value(int64(*app.MaxConnections))
	} else {
		data.MaxConnections = types.Int64Null()
	}
	if app.AppKey != nil {
		data.AppKey = types.StringValue(*app.AppKey)
	} else {
		data.AppKey = types.StringNull()
	}
	if app.Status != nil {
		data.Status = types.StringValue(*app.Status)
	} else {
		data.Status = types.StringNull()
	}
	if app.CreatedAt != nil {
		data.CreatedAt = types.StringValue(*app.CreatedAt)
	} else {
		data.CreatedAt = types.StringNull()
	}

	// Persist to state.
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Compile-time interface assertions.
var (
	_ datasource.DataSource              = (*WebsocketAppDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*WebsocketAppDataSource)(nil)
)
